nicer output

diff --git a/pkg_src_fetch b/pkg_src_fetch
--- a/pkg_src_fetch
+++ b/pkg_src_fetch
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+TMPFILE=/tmp/fetchsrclog.$$
+
 function checkpkg {
     local rc
 
@@ -29,5 +31,14 @@ while [ "$1" ]; do
     [ -d "/var/lib/build/staging/$pkg" ] && export PKGDIR="/var/lib/build/staging/$pkg"
     [ -d "/var/lib/build/all/$pkg" ] && export PKGDIR="/var/lib/build/all/$pkg"
     
-    [ "$PKGDIR" ] && [ -f "$PKGDIR/Fetch-source.sh" ] && (cd $PKGDIR; PATH="/var/lib/build:$PATH" "./Fetch-source.sh")
+    if [ "$PKGDIR" ] && [ -f "$PKGDIR/Fetch-source.sh" ]; then
+        if ! (cd $PKGDIR; PATH="/var/lib/build:$PATH" "./Fetch-source.sh" &> $TMPFILE); then
+                echo "## Failed to fetch source for $pkg!"
+		echo
+		cat $TMPFILE
+		echo
+        fi
+    fi
 done
+
+rm -f $TMPFILE
