recursive building

diff --git a/pkg_build b/pkg_build
--- a/pkg_build
+++ b/pkg_build
@@ -1,9 +1,17 @@
 #!/bin/bash
 
+# Maximum number of recursive builds
+MR=4
+
 [ -d /proc/self/fd ] || exit 1
 [ -d /dev/fd ] || exit 1
 [ -c /dev/null ] || exit 1
 [ -c /dev/zero ] || exit 1
+
+if [ "$1" = '-r' ]; then
+    export RECURSIVEBUILD=yes
+    shift
+fi
 
 if [ -z "$1" ]; then
    echo "Usage: pkg_build <pkg> ..."
@@ -38,6 +46,7 @@ mkdir -p /var/log/build
 mkdir -p /var/log/config
 
 while [ "$1" ]; do
+    n=0
     pkg=$(basename $1)
     shift
     
@@ -48,19 +57,32 @@ while [ "$1" ]; do
     [ -d "/var/lib/build/all/$pkg" ] && export PKGDIR="/var/lib/build/all/$pkg"
     cd $PKGDIR
     
-    rm -f /var/log/build/$pkg.log
-    # Save current stdout to file descriptor 3, and redirect stdout to tee
-    exec 3>&1 > >(tee -a "/var/log/build/$pkg.log")
-
-    echo "Building $pkg from $PKGDIR"
-    PATH="/var/lib/build:$PATH" ./Build.sh 2>&1
-    rc=$?
-    if [ $rc != 0 ]; then
-	echo "ERROR: Build unsuccessful [$rc]. See /var/log/build/$pkg.log"
-    else
-	echo "$pkg done!"
-    fi
-    
+    while true; do
+	rm -f /var/log/build/$pkg.log
+        # Save current stdout to file descriptor 3, and redirect stdout to tee
+	exec 3>&1 > >(tee -a "/var/log/build/$pkg.log")
+	
+	echo "Building $pkg from $PKGDIR"
+	PATH="/var/lib/build:$PATH" ./Build.sh 2>&1
+	rc=$?
+	if [ $rc != 0 ]; then
+	    if [ "$RECURSIVEBUILD" = yes ]; then
+		if [ $rc = 2 ]; then
+		    n=$[ n+1 ]
+		    if [ $n -lt $MR ]; then
+			exec 1>&3 3>&-
+			continue
+		    fi
+		    echo "Maximum number of recursive builds ($MR) exceeded!"
+		fi
+	    fi
+	    echo "ERROR: Build unsuccessful [$rc]. See /var/log/build/$pkg.log"
+	else
+	    echo "$pkg done!"
+	fi
+	break
+    done
+	
     # Restore stdout and close file descriptor 3
     exec 1>&3 3>&-
 done
